version: 0.0
os: linux

files:
  - source: /
    destination:  /opt/codedeploy-agent/deployment-root/a6db02a0-65a9-41ad-87b3-1cf7fa3c6c6c/d-YKYTRCJRA/deployment-archive/scripts

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: fix_privileges.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: server_start.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: server_stop.sh
      timeout: 20
      runas: ec2-user